package com.battery.core.models;

import java.util.Date;

public class GprsList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rcv_gprs_list.gprs_id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private String gprsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rcv_gprs_list.link_status
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Integer linkStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rcv_gprs_list.port
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Integer port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rcv_gprs_list.update_time
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rcv_gprs_list.gprs_id
     *
     * @return the value of rcv_gprs_list.gprs_id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public String getGprsId() {
        return gprsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rcv_gprs_list.gprs_id
     *
     * @param gprsId the value for rcv_gprs_list.gprs_id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setGprsId(String gprsId) {
        this.gprsId = gprsId == null ? null : gprsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rcv_gprs_list.link_status
     *
     * @return the value of rcv_gprs_list.link_status
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Integer getLinkStatus() {
        return linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rcv_gprs_list.link_status
     *
     * @param linkStatus the value for rcv_gprs_list.link_status
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setLinkStatus(Integer linkStatus) {
        this.linkStatus = linkStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rcv_gprs_list.port
     *
     * @return the value of rcv_gprs_list.port
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rcv_gprs_list.port
     *
     * @param port the value for rcv_gprs_list.port
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rcv_gprs_list.update_time
     *
     * @return the value of rcv_gprs_list.update_time
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rcv_gprs_list.update_time
     *
     * @param updateTime the value for rcv_gprs_list.update_time
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}