package com.battery.core.models;

import java.util.Date;

public class OtaSendInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.gprs_id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private String gprsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.target
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Integer target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.bin_file_path
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private String binFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.firmware
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Integer firmware;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.version
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.slave_indexes
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private String slaveIndexes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.send_done
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Integer sendDone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.result_info
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private String resultInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ota_send.update_time
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.id
     *
     * @return the value of ota_send.id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.id
     *
     * @param id the value for ota_send.id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.gprs_id
     *
     * @return the value of ota_send.gprs_id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public String getGprsId() {
        return gprsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.gprs_id
     *
     * @param gprsId the value for ota_send.gprs_id
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setGprsId(String gprsId) {
        this.gprsId = gprsId == null ? null : gprsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.target
     *
     * @return the value of ota_send.target
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.target
     *
     * @param target the value for ota_send.target
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setTarget(Integer target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.bin_file_path
     *
     * @return the value of ota_send.bin_file_path
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public String getBinFilePath() {
        return binFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.bin_file_path
     *
     * @param binFilePath the value for ota_send.bin_file_path
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setBinFilePath(String binFilePath) {
        this.binFilePath = binFilePath == null ? null : binFilePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.firmware
     *
     * @return the value of ota_send.firmware
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Integer getFirmware() {
        return firmware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.firmware
     *
     * @param firmware the value for ota_send.firmware
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setFirmware(Integer firmware) {
        this.firmware = firmware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.version
     *
     * @return the value of ota_send.version
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.version
     *
     * @param version the value for ota_send.version
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.slave_indexes
     *
     * @return the value of ota_send.slave_indexes
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public String getSlaveIndexes() {
        return slaveIndexes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.slave_indexes
     *
     * @param slaveIndexes the value for ota_send.slave_indexes
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setSlaveIndexes(String slaveIndexes) {
        this.slaveIndexes = slaveIndexes == null ? null : slaveIndexes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.send_done
     *
     * @return the value of ota_send.send_done
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Integer getSendDone() {
        return sendDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.send_done
     *
     * @param sendDone the value for ota_send.send_done
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setSendDone(Integer sendDone) {
        this.sendDone = sendDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.result_info
     *
     * @return the value of ota_send.result_info
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public String getResultInfo() {
        return resultInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.result_info
     *
     * @param resultInfo the value for ota_send.result_info
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setResultInfo(String resultInfo) {
        this.resultInfo = resultInfo == null ? null : resultInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ota_send.update_time
     *
     * @return the value of ota_send.update_time
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ota_send.update_time
     *
     * @param updateTime the value for ota_send.update_time
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}