package com.battery.core.mapper;

import com.battery.core.models.GprsList;

public interface GprsListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcv_gprs_list
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int deleteByPrimaryKey(String gprsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcv_gprs_list
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int insert(GprsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcv_gprs_list
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int insertSelective(GprsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcv_gprs_list
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    GprsList selectByPrimaryKey(String gprsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcv_gprs_list
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int updateByPrimaryKeySelective(GprsList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rcv_gprs_list
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int updateByPrimaryKey(GprsList record);
}