package com.battery.core.mapper;

import com.battery.core.models.OtaSendInfo;

public interface OtaSendInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ota_send
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ota_send
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int insert(OtaSendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ota_send
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int insertSelective(OtaSendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ota_send
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    OtaSendInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ota_send
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int updateByPrimaryKeySelective(OtaSendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ota_send
     *
     * @mbggenerated Thu Jan 17 10:01:48 CST 2019
     */
    int updateByPrimaryKey(OtaSendInfo record);
}