package com.battery.core.vo.search;

import java.math.BigDecimal;
import java.util.Date;

import com.battery.common.vo.search.PageEntity;
import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by Bill Generator. This class corresponds to the
 * database table gprs_config_info 基站gprs参数配置表
 *
 * @zdmgenerated 2017-42-28 07:42
 */
@ApiModel(value = "基站gprs参数配置表查询", description = "基站gprs参数配置表查询描述")
public class SearchGprsDeviceInfoPagingVo extends PageEntity {
    /**
     * @Fields id 
     */
    private Integer id;
    /**
     * @Fields gprsId 
     */
    private String gprsId;
    /**
     * @Fields gprsIdOut 
     */
    private String gprsIdOut;
    /**
     * @Fields deviceType 设备类型编号 fk
            
     */
    private Integer deviceType;
    /**
     * @Fields rcvTime 
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date rcvTime;
    /**
     * @Fields linkStatus 设备在线状态,0离线,1在线
     */
    private Boolean linkStatus;
    /**
     * @Fields companyId3 三级公司id
     */
    private Integer companyId3;
    /**
     * @Fields gprsFlag 主机类型标志1 备用主机0配套主机
     */
    private Integer gprsFlag;
    /**
     * @Fields gprsPort 主机端口，备注，适配器通信不需要通过该字段决定。
     */
    private String gprsPort;
    /**
     * @Fields gprsSpec 主机规格
     */
    private String gprsSpec;
    /**
     * @Fields subDeviceCount 从机总数
     */
    private Integer subDeviceCount;
    /**
     * @Fields validDay 有效天数
     */
    private Integer validDay;
    /**
     * @Fields hallFlag 霍尔感应器，1有，2无
     */
    private Integer hallFlag;
    /**
     * @Fields connectionType 连接属性-> 1：短连接，无需保活帧；2：长连接，需要保活帧
     */
    private Integer connectionType;
    /**
     * @Fields heartbeatInterval 心跳间隔，如果为0则为短链接,单位秒
     */
    private Integer heartbeatInterval;
    /**
     * @Fields floatInterval 浮充状态下状态帧传输间隔，单位秒
     */
    private Integer floatInterval;
    /**
     * @Fields dischargeInterval 放电状态下状态帧传输间隔，单位秒
     */
    private Integer dischargeInterval;
    /**
     * @Fields chargeInterval 充电状态下状态帧传输间隔，单位秒
     */
    private Integer chargeInterval;
    /**
     * @Fields fastSampleInterval 快速采样间隔（区间1和3）， 0：5ms; 1: 10ms; 2: 20ms; 3: 40ms
     */
    private Integer fastSampleInterval;
    /**
     * @Fields slowSampleInterval 慢速采样间隔（区间1和3）， 0：1s; 1: 5s; 2: 10s; 3: 20s
     */
    private Integer slowSampleInterval;
    /**
     * @Fields dischargeTime 区间2时间， 0：1s; 1: 2s; 2: 3s; 3: 4s
     */
    private Integer dischargeTime;
    /**
     * @Fields slowSampleTime 慢采集采样时间（区间5）， 0：1s; 1: 2s; 2: 3s; 3: 4s
     */
    private Integer slowSampleTime;
    /**
     * @Fields consoleCellCapError 单体电池故障容量%
     */
    private BigDecimal consoleCellCapError;
    /**
     * @Fields consoleCellCapNormal 单体电池正常容量%
     */
    private BigDecimal consoleCellCapNormal;
    /**
     * @Fields durationExcellent 时长性能:优
     */
    private Integer durationExcellent;
    /**
     * @Fields durationGood 时长性能:良
     */
    private Integer durationGood;
    /**
     * @Fields durationMedium 时长性能:中
     */
    private Integer durationMedium;
    /**
     * @Fields validDischargeVol 有效放电截止电压 
     */
    private BigDecimal validDischargeVol;
    /**
     * @Fields validChargeVol 有效充电截止电压
     */
    private BigDecimal validChargeVol;
    /**
     * @Fields validDischargeCur 有效放电电流
     */
    private BigDecimal validDischargeCur;
    /**
     * @Fields validChargeCur 有效充电电流
     */
    private BigDecimal validChargeCur;
    /**
     * @Fields downCur 掉电电流
     */
    private BigDecimal downCur;
    /**
     * @Fields downVol 掉电电压
     */
    private BigDecimal downVol;
    /**
     * @Fields marginTime 整冶余量时长
     */
    private BigDecimal marginTime;
    /**
     * @Fields suggestTime 整治时长
     */
    private String suggestTime;
    /**
     * @Fields suggestCellCapPercent 建议整治单体预测容量百分比
     */
    private String suggestCellCapPercent;
    /**
     * @Fields suggestResistThreshold 单体整治内阻阈值
     */
    private BigDecimal suggestResistThreshold;
    /**
     * @Fields suggestDurationPercent 放电时长有效百分比，%
     */
    private Integer suggestDurationPercent;
    /**
     * @Fields suggestLoadCurThreshold 扩容电流阈值，A
     */
    private BigDecimal suggestLoadCurThreshold;
    /**
     * @Fields maxDischargeCur 有效放电电流，最大值
     */
    private BigDecimal maxDischargeCur;
    /**
     * @Fields volHighWarningThreshold 总电压过高告警阈值,V
     */
    private BigDecimal volHighWarningThreshold;
    /**
     * @Fields dischargeThreshold 放电判断阈值
     */
    private BigDecimal dischargeThreshold;
    /**
     * @Fields chargeThreshold 充电判断阈值，单位V
     */
    private BigDecimal chargeThreshold;
    /**
     * @Fields volLowWarningThreshold 总电压过低告警阈值 V
     */
    private BigDecimal volLowWarningThreshold;
    /**
     * @Fields currentWarningToplimit 电流异常告警上限
     */
    private BigDecimal currentWarningToplimit;
    /**
     * @Fields currentWarningLowerlimit 电流异常告警下限
     */
    private BigDecimal currentWarningLowerlimit;
    /**
     * @Fields singleHighVolThreshold 单体过压告警阈值
     */
    private BigDecimal singleHighVolThreshold;
    /**
     * @Fields singleLowVolThreshold 单体欠压告警阈值
     */
    private BigDecimal singleLowVolThreshold;
    /**
     * @Fields temHighWarningThreshold 温度过高告警阈值 ℃
     */
    private Integer temHighWarningThreshold;
    /**
     * @Fields temLowWarningThreshold 温度过低告警阈值
     */
    private Integer temLowWarningThreshold;
    /**
     * @Fields socLowWarningThreshold SOC过低告警阈值
     */
    private Integer socLowWarningThreshold;
    /**
     * @Fields highVolRecover 总电压过压恢复点
     */
    private BigDecimal highVolRecover;
    /**
     * @Fields lowVolRecover 总电压欠压恢复点
     */
    private BigDecimal lowVolRecover;
    /**
     * @Fields singleHighVolRecover 单体过压恢复点
     */
    private BigDecimal singleHighVolRecover;
    /**
     * @Fields singleLowVolRecover 单体欠压恢复点
     */
    private BigDecimal singleLowVolRecover;
    /**
     * @Fields highSurroundingtemWarningThreshold 环境高温告警阈值
     */
    private Integer highSurroundingtemWarningThreshold;
    /**
     * @Fields lowSurroundingtemWarningThreshold 环境低温告警阈值
     */
    private Integer lowSurroundingtemWarningThreshold;
    /**
     * @Fields highSurroundingtemWarningRecover 环境高温告警恢复点
     */
    private Integer highSurroundingtemWarningRecover;
    /**
     * @Fields lowSurroundingtemWarningRecover 环境低温告警恢复点
     */
    private Integer lowSurroundingtemWarningRecover;
    /**
     * @Fields hightemWarningRecover 单体高温告警恢复点
     */
    private Integer hightemWarningRecover;
    /**
     * @Fields lowtemWarningRecover 单体低温告警恢复点
     */
    private Integer lowtemWarningRecover;
    /**
     * @Fields lowSocRecover soc过低
     */
    private Integer lowSocRecover;
    
	@ApiModelProperty(value = "true相等,false不相等")
	private boolean equalType = true;

	private Integer volLevel;
	/**
	 * 筛选单体标准（0，满足时长要求，1，仅故障单体）
	 */
	private Integer chooseCellStandard;
	
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGprsId() {
        return gprsId;
    }

    public void setGprsId(String gprsId) {
        this.gprsId = gprsId == null ? null : gprsId.trim();
    }

    public String getGprsIdOut() {
        return gprsIdOut;
    }

    public void setGprsIdOut(String gprsIdOut) {
        this.gprsIdOut = gprsIdOut == null ? null : gprsIdOut.trim();
    }

    public Integer getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    public Date getRcvTime() {
        return rcvTime;
    }

    public void setRcvTime(Date rcvTime) {
        this.rcvTime = rcvTime;
    }

    public Boolean getLinkStatus() {
        return linkStatus;
    }

    public void setLinkStatus(Boolean linkStatus) {
        this.linkStatus = linkStatus;
    }

    public Integer getCompanyId3() {
        return companyId3;
    }

    public void setCompanyId3(Integer companyId3) {
        this.companyId3 = companyId3;
    }

    public Integer getGprsFlag() {
        return gprsFlag;
    }

    public void setGprsFlag(Integer gprsFlag) {
        this.gprsFlag = gprsFlag;
    }

    public String getGprsPort() {
        return gprsPort;
    }

    public void setGprsPort(String gprsPort) {
        this.gprsPort = gprsPort == null ? null : gprsPort.trim();
    }

    public String getGprsSpec() {
        return gprsSpec;
    }

    public void setGprsSpec(String gprsSpec) {
        this.gprsSpec = gprsSpec == null ? null : gprsSpec.trim();
    }

    public Integer getSubDeviceCount() {
        return subDeviceCount;
    }

    public void setSubDeviceCount(Integer subDeviceCount) {
        this.subDeviceCount = subDeviceCount;
    }

    public Integer getValidDay() {
        return validDay;
    }

    public void setValidDay(Integer validDay) {
        this.validDay = validDay;
    }

    public Integer getHallFlag() {
        return hallFlag;
    }

    public void setHallFlag(Integer hallFlag) {
        this.hallFlag = hallFlag;
    }

    public Integer getConnectionType() {
        return connectionType;
    }

    public void setConnectionType(Integer connectionType) {
        this.connectionType = connectionType;
    }

    public Integer getHeartbeatInterval() {
        return heartbeatInterval;
    }

    public void setHeartbeatInterval(Integer heartbeatInterval) {
        this.heartbeatInterval = heartbeatInterval;
    }

    public Integer getFloatInterval() {
        return floatInterval;
    }

    public void setFloatInterval(Integer floatInterval) {
        this.floatInterval = floatInterval;
    }

    public Integer getDischargeInterval() {
        return dischargeInterval;
    }

    public void setDischargeInterval(Integer dischargeInterval) {
        this.dischargeInterval = dischargeInterval;
    }

    public Integer getChargeInterval() {
        return chargeInterval;
    }

    public void setChargeInterval(Integer chargeInterval) {
        this.chargeInterval = chargeInterval;
    }

    public Integer getFastSampleInterval() {
        return fastSampleInterval;
    }

    public void setFastSampleInterval(Integer fastSampleInterval) {
        this.fastSampleInterval = fastSampleInterval;
    }

    public Integer getSlowSampleInterval() {
        return slowSampleInterval;
    }

    public void setSlowSampleInterval(Integer slowSampleInterval) {
        this.slowSampleInterval = slowSampleInterval;
    }

    public Integer getDischargeTime() {
        return dischargeTime;
    }

    public void setDischargeTime(Integer dischargeTime) {
        this.dischargeTime = dischargeTime;
    }

    public Integer getSlowSampleTime() {
        return slowSampleTime;
    }

    public void setSlowSampleTime(Integer slowSampleTime) {
        this.slowSampleTime = slowSampleTime;
    }

    public BigDecimal getConsoleCellCapError() {
        return consoleCellCapError;
    }

    public void setConsoleCellCapError(BigDecimal consoleCellCapError) {
        this.consoleCellCapError = consoleCellCapError;
    }

    public BigDecimal getConsoleCellCapNormal() {
        return consoleCellCapNormal;
    }

    public void setConsoleCellCapNormal(BigDecimal consoleCellCapNormal) {
        this.consoleCellCapNormal = consoleCellCapNormal;
    }

    public Integer getDurationExcellent() {
        return durationExcellent;
    }

    public void setDurationExcellent(Integer durationExcellent) {
        this.durationExcellent = durationExcellent;
    }

    public Integer getDurationGood() {
        return durationGood;
    }

    public void setDurationGood(Integer durationGood) {
        this.durationGood = durationGood;
    }

    public Integer getDurationMedium() {
        return durationMedium;
    }

    public void setDurationMedium(Integer durationMedium) {
        this.durationMedium = durationMedium;
    }

    public BigDecimal getValidDischargeVol() {
        return validDischargeVol;
    }

    public void setValidDischargeVol(BigDecimal validDischargeVol) {
        this.validDischargeVol = validDischargeVol;
    }

    public BigDecimal getValidChargeVol() {
        return validChargeVol;
    }

    public void setValidChargeVol(BigDecimal validChargeVol) {
        this.validChargeVol = validChargeVol;
    }

    public BigDecimal getValidDischargeCur() {
        return validDischargeCur;
    }

    public void setValidDischargeCur(BigDecimal validDischargeCur) {
        this.validDischargeCur = validDischargeCur;
    }

    public BigDecimal getValidChargeCur() {
        return validChargeCur;
    }

    public void setValidChargeCur(BigDecimal validChargeCur) {
        this.validChargeCur = validChargeCur;
    }

    public BigDecimal getDownCur() {
        return downCur;
    }

    public void setDownCur(BigDecimal downCur) {
        this.downCur = downCur;
    }

    public BigDecimal getDownVol() {
        return downVol;
    }

    public void setDownVol(BigDecimal downVol) {
        this.downVol = downVol;
    }

    public BigDecimal getMarginTime() {
        return marginTime;
    }

    public void setMarginTime(BigDecimal marginTime) {
        this.marginTime = marginTime;
    }

    public String getSuggestTime() {
        return suggestTime;
    }

    public void setSuggestTime(String suggestTime) {
        this.suggestTime = suggestTime == null ? null : suggestTime.trim();
    }

    public String getSuggestCellCapPercent() {
        return suggestCellCapPercent;
    }

    public void setSuggestCellCapPercent(String suggestCellCapPercent) {
        this.suggestCellCapPercent = suggestCellCapPercent == null ? null : suggestCellCapPercent.trim();
    }

    public BigDecimal getSuggestResistThreshold() {
        return suggestResistThreshold;
    }

    public void setSuggestResistThreshold(BigDecimal suggestResistThreshold) {
        this.suggestResistThreshold = suggestResistThreshold;
    }

    public Integer getSuggestDurationPercent() {
        return suggestDurationPercent;
    }

    public void setSuggestDurationPercent(Integer suggestDurationPercent) {
        this.suggestDurationPercent = suggestDurationPercent;
    }

    public BigDecimal getSuggestLoadCurThreshold() {
        return suggestLoadCurThreshold;
    }

    public void setSuggestLoadCurThreshold(BigDecimal suggestLoadCurThreshold) {
        this.suggestLoadCurThreshold = suggestLoadCurThreshold;
    }

    public BigDecimal getMaxDischargeCur() {
        return maxDischargeCur;
    }

    public void setMaxDischargeCur(BigDecimal maxDischargeCur) {
        this.maxDischargeCur = maxDischargeCur;
    }

    public BigDecimal getVolHighWarningThreshold() {
        return volHighWarningThreshold;
    }

    public void setVolHighWarningThreshold(BigDecimal volHighWarningThreshold) {
        this.volHighWarningThreshold = volHighWarningThreshold;
    }

    public BigDecimal getDischargeThreshold() {
        return dischargeThreshold;
    }

    public void setDischargeThreshold(BigDecimal dischargeThreshold) {
        this.dischargeThreshold = dischargeThreshold;
    }

    public BigDecimal getChargeThreshold() {
        return chargeThreshold;
    }

    public void setChargeThreshold(BigDecimal chargeThreshold) {
        this.chargeThreshold = chargeThreshold;
    }

    public BigDecimal getVolLowWarningThreshold() {
        return volLowWarningThreshold;
    }

    public void setVolLowWarningThreshold(BigDecimal volLowWarningThreshold) {
        this.volLowWarningThreshold = volLowWarningThreshold;
    }

    public BigDecimal getCurrentWarningToplimit() {
        return currentWarningToplimit;
    }

    public void setCurrentWarningToplimit(BigDecimal currentWarningToplimit) {
        this.currentWarningToplimit = currentWarningToplimit;
    }

    public BigDecimal getCurrentWarningLowerlimit() {
        return currentWarningLowerlimit;
    }

    public void setCurrentWarningLowerlimit(BigDecimal currentWarningLowerlimit) {
        this.currentWarningLowerlimit = currentWarningLowerlimit;
    }

    public BigDecimal getSingleHighVolThreshold() {
        return singleHighVolThreshold;
    }

    public void setSingleHighVolThreshold(BigDecimal singleHighVolThreshold) {
        this.singleHighVolThreshold = singleHighVolThreshold;
    }

    public BigDecimal getSingleLowVolThreshold() {
        return singleLowVolThreshold;
    }

    public void setSingleLowVolThreshold(BigDecimal singleLowVolThreshold) {
        this.singleLowVolThreshold = singleLowVolThreshold;
    }

    public Integer getTemHighWarningThreshold() {
        return temHighWarningThreshold;
    }

    public void setTemHighWarningThreshold(Integer temHighWarningThreshold) {
        this.temHighWarningThreshold = temHighWarningThreshold;
    }

    public Integer getTemLowWarningThreshold() {
        return temLowWarningThreshold;
    }

    public void setTemLowWarningThreshold(Integer temLowWarningThreshold) {
        this.temLowWarningThreshold = temLowWarningThreshold;
    }

    public Integer getSocLowWarningThreshold() {
        return socLowWarningThreshold;
    }

    public void setSocLowWarningThreshold(Integer socLowWarningThreshold) {
        this.socLowWarningThreshold = socLowWarningThreshold;
    }

    public BigDecimal getHighVolRecover() {
        return highVolRecover;
    }

    public void setHighVolRecover(BigDecimal highVolRecover) {
        this.highVolRecover = highVolRecover;
    }

    public BigDecimal getLowVolRecover() {
        return lowVolRecover;
    }

    public void setLowVolRecover(BigDecimal lowVolRecover) {
        this.lowVolRecover = lowVolRecover;
    }

    public BigDecimal getSingleHighVolRecover() {
        return singleHighVolRecover;
    }

    public void setSingleHighVolRecover(BigDecimal singleHighVolRecover) {
        this.singleHighVolRecover = singleHighVolRecover;
    }

    public BigDecimal getSingleLowVolRecover() {
        return singleLowVolRecover;
    }

    public void setSingleLowVolRecover(BigDecimal singleLowVolRecover) {
        this.singleLowVolRecover = singleLowVolRecover;
    }

    public Integer getHighSurroundingtemWarningThreshold() {
        return highSurroundingtemWarningThreshold;
    }

    public void setHighSurroundingtemWarningThreshold(Integer highSurroundingtemWarningThreshold) {
        this.highSurroundingtemWarningThreshold = highSurroundingtemWarningThreshold;
    }

    public Integer getLowSurroundingtemWarningThreshold() {
        return lowSurroundingtemWarningThreshold;
    }

    public void setLowSurroundingtemWarningThreshold(Integer lowSurroundingtemWarningThreshold) {
        this.lowSurroundingtemWarningThreshold = lowSurroundingtemWarningThreshold;
    }

    public Integer getHighSurroundingtemWarningRecover() {
        return highSurroundingtemWarningRecover;
    }

    public void setHighSurroundingtemWarningRecover(Integer highSurroundingtemWarningRecover) {
        this.highSurroundingtemWarningRecover = highSurroundingtemWarningRecover;
    }

    public Integer getLowSurroundingtemWarningRecover() {
        return lowSurroundingtemWarningRecover;
    }

    public void setLowSurroundingtemWarningRecover(Integer lowSurroundingtemWarningRecover) {
        this.lowSurroundingtemWarningRecover = lowSurroundingtemWarningRecover;
    }

    public Integer getHightemWarningRecover() {
        return hightemWarningRecover;
    }

    public void setHightemWarningRecover(Integer hightemWarningRecover) {
        this.hightemWarningRecover = hightemWarningRecover;
    }

    public Integer getLowtemWarningRecover() {
        return lowtemWarningRecover;
    }

    public void setLowtemWarningRecover(Integer lowtemWarningRecover) {
        this.lowtemWarningRecover = lowtemWarningRecover;
    }

    public Integer getLowSocRecover() {
        return lowSocRecover;
    }

    public void setLowSocRecover(Integer lowSocRecover) {
        this.lowSocRecover = lowSocRecover;
  
    }

	public boolean isEqualType() {
		return equalType;
	}

	public void setEqualType(boolean equalType) {
		this.equalType = equalType;
	}

	public Integer getVolLevel() {
		return volLevel;
	}

	public void setVolLevel(Integer volLevel) {
		this.volLevel = volLevel;
	}

	public Integer getChooseCellStandard() {
		return chooseCellStandard;
	}

	public void setChooseCellStandard(Integer chooseCellStandard) {
		this.chooseCellStandard = chooseCellStandard;
	}
	
}