profile: test

spring:  
  profiles: test
  datasource:
    readSize: 1
    type: com.alibaba.druid.pool.DruidDataSource
    master: 
      name: master
      url: jdbc:mysql://192.168.31.200:1024/ota_service?useSSL=false
      username: amplifi
      password: Cc8EY9T6IPNko8XioPqvWg==
      # 使用druid数据源
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 800
      initialSize: 20
      maxWait: 60000
      minIdle: 20
      timeBetweenEvictionRunsMillis: 3600000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 150
      maxPoolPreparedStatementPerConnectionSize: 150 
      defaultAutoCommit: false
      connectionProperties: password=Cc8EY9T6IPNko8XioPqvWg==;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    slave1: 
      name: slave1
      url: jdbc:mysql://192.168.31.200:1024/ota_service?useSSL=false
      username: amplifi
      password: Cc8EY9T6IPNko8XioPqvWg==
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 800
      initialSize: 20
      maxWait: 60000
      minIdle: 20
      timeBetweenEvictionRunsMillis: 3600000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 150
      maxPoolPreparedStatementPerConnectionSize: 150 
      defaultAutoCommit: false
      connectionProperties: password=Cc8EY9T6IPNko8XioPqvWg==;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.battery.core.models
  config: classpath:mybatis/mybatis-config.xml
  
# redis配置
redis: 
  host: 127.0.0.1
  port: 8901
  pass: root
  max:
    total: 300
    idle: 100
    waitMillis: 1000
  test: 
    on_borrow: true

#报告存储地址     
reportPic: 
  parentPath: D:/整治报告图片
reportWord:
  parentPath: D:/整治报告
reportZip:  
  parentPath: D:/电池整治报告.zip
renovateSuggest: 
  parentPath: D:/设备维护建议
fileName: nbc

management: 
  port: 54001
  context-path: /manage

security:
  user:  
    name: admin
    password: admin